### PR TITLE
Fix for not being able to write on >SMB1

### LINKED ISSUE #87: Cannot write files into samba share
I have found that since this 
[commit](https://github.com/GoogleChrome/chromeos_network_file_share/commit/58a82cead928bb50460191fccd7fb048c71ffe0b), I cannot write files into a samba share. I believe this is due to us overwriting `smb.conf` and missing a value that lets us write into the share.

Some of the things that I have found:

- Unmounting `/etc/samba/.smb` does not make a difference.
- `writeable = yes` and `read only = no` does not help in the case (still cannot write)

I am looking into this further today

### PR DESCRIPTION
**Pull request by allenktv**
Fixes #87

### CODE REVIEW

File: nacl/SambaFsp.cc [hunk 1]
```diff
@@ -356,6 +356,11 @@ void SambaFsp::LogErrorAndSetErrorResult(std::string operationName,
       // retry but once retrying fails to respond with a valid error code.
       errorString = "SHOULD_RETRY";
       break;
+    case EINVAL:
+      if (operationName == "getMetadataEntry:smbc_stat") {
```
Comment (illiminable) [inline nacl/SambaFsp.cc]: Can you add an else and explicitly set to failed and not fall through to the next case. 

When the case is empty, falling through is ok, but otherwise at the least it should be documented. Though in this case I think its better to just be explicit since there isn't much value to falling through and its better than the risk of someone adding another case between this and default without noticing. Plus if another conditional case like this is needed in future both wouldn't be able to fall through.

Comment (allenktv) [inline nacl/SambaFsp.cc]: Will do

File: nacl/SambaFsp.cc [hunk 2]
```diff
@@ -356,6 +356,14 @@ void SambaFsp::LogErrorAndSetErrorResult(std::string operationName,
...
+        errorString = "NOT_FOUND";
+        break;
```
Comment (illiminable) [inline nacl/SambaFsp.cc]: Only need one break at the end.
